image: maven:3.8.3-jdk-11
stages:
  - build
  - sonarqube-check 
  - test
  - deploy
build:
  stage: build
  script:
    - C:\Users\HP\Downloads\apache-maven-3.9.6\bin\mvn clean package -DskipTests

