stages:
  - prepare
  - build
  - test
  - execute_template

prepare_template:
  stage: prepare
  script:
   - 'Invoke-WebRequest -Uri "http://localhost:8082/artifactory/TemplateYml/.gitlab-ci-template.yml" -OutFile ".gitlab-ci-template.yml" -Credential (New-Object System.Management.Automation.PSCredential("admin", (ConvertTo-SecureString "Zayneb@123" -AsPlainText -Force)))'

  artifacts:
    paths:
      - .gitlab-ci-template.yml

execute_template:
  stage: execute_template  # Assurez-vous que ce job est exécuté après le job de préparation
  script:
    - "powershell -Command 'Invoke-Expression (Get-Content .gitlab-ci-template.yml -Raw)'"
  dependencies:
    - prepare_template