

stages:
  - build
  - sonarqube-check
  - test
  - deploy

build:
  stage: build
  image: maven:3.8.3-jdk-11
  script:
    - mvn clean package -DskipTests

sonarqube-check:
  stage: sonarqube-check
  image: maven:3-eclipse-temurin-17
 
 
  script:
  - mvn sonar:sonar  -DskipTests


