stages:
  - prepare
  - build
  - test

prepare_template:
  stage: prepare
  script:
   - 'Invoke-WebRequest -Uri "http://localhost:8082/artifactory/TemplateYml/.gitlab-ci-template.yml" -OutFile ".gitlab-ci-template.yml" -Credential (New-Object System.Management.Automation.PSCredential("admin", (ConvertTo-SecureString "Zayneb@123" -AsPlainText -Force)))'

  artifacts:
    paths:
      - .gitlab-ci-template.yml

