
include:
  - project: $PROJECT_NAME
    file: $FILE_PATH  


build:
  extends: .build_job

sonarqube-check:
  extends: .sonarqube_job

deploy_Dev:
  extends: .deploy_develop
  only:
    - Develop
deploy_Staging:
  extends: .deploy_Staging
  only:
    - Staging
deploy_Product:
  extends: .deploy_Product
  only:
    - main   

