stages:
  - test

test_job:
  stage: test
  image: registry.gitlab.com/fatmasamaali/pipe/my-powershell-maven-image
  script:
    - echo "Hello, GitLab Runner!"
    - mvn --version
    - pwsh -Command "Write-Output 'PowerShell is working!'"
