include:
  - project: 'fatmasamaali/TemplateYmlFinal'
    file: '/.gitlab-ci-template.yml'

build:
  extends: .build_job

unit-tests:
  extends: .test_job

sonarqube-check:
  extends: .sonarqube_job

deploy_sandbox:
  extends: .deploy_job