stages:
  - build
  # Add other stages as needed

build-with-maven:
  stage: build
  script:
    - mvn clean install
  tags:
    - docker-runner
  except:
    - branches

run-powershell-script:
  stage: build
  script:
    - powershell.exe .\scripts\my_script.ps1
  tags:
    - docker-runner
  except:
    - branches

# Define other jobs as needed

after_script:
  - >
    powershell.exe -Command "
      if (\$CI_JOB_STATUS -eq \"failed\") {
        # Your failure handling logic here
      }
    "
