image: maven:3.8.6-jdk-11 

include:
  - project: $PROJECT_NAME
    file: $FILE_PATH  
     
stages:
  - build
  - test
  - sonarqube-check
  - deploy


build:
  stage: build
  script:
    - mvn -s $CI_PROJECT_DIR/ci-settings.xml clean package -DskipTests 

sonarqube-check:
  extends: .sonarqube_job

deploy_Dev:
  extends: .deploy_develop
  only:
    - Develop
deploy_Staging:
  extends: .deploy_Staging
  only:
    - Staging
deploy_Product:
  extends: .deploy_Product
  only:
    - main   

